[package]
name = "fathom"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.38.0"
features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_LibraryLoader", "Win32_Graphics_Gdi"]

